# Generated by Django 5.2.5 on 2025-11-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepagesection_specialization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='section_name',
            field=models.CharField(choices=[('hero', 'Hero Section'), ('features', 'Features'), ('services', 'Services'), ('case_studies', 'Case Studies'), ('testimonials', 'Testimonials'), ('websites', 'Doctor Websites'), ('blog', 'Blog Posts'), ('counters', 'Statistics')], max_length=50, unique=True),
        ),
    ]
