# Generated by Django 5.2.5 on 2025-10-23 20:43

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_analytics_id', models.CharField(blank=True, max_length=20, null=True)),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=20, null=True)),
                ('track_user_behavior', models.BooleanField(default=True)),
                ('track_heatmaps', models.BooleanField(default=False)),
                ('track_scroll_depth', models.BooleanField(default=True)),
                ('track_form_interactions', models.BooleanField(default=True)),
                ('track_outbound_links', models.BooleanField(default=True)),
                ('anonymize_ip', models.BooleanField(default=True)),
                ('cookie_consent_required', models.BooleanField(default=True)),
                ('data_retention_days', models.PositiveIntegerField(default=365)),
            ],
            options={
                'verbose_name': 'Analytics Settings',
                'verbose_name_plural': 'Analytics Settings',
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('avg_session_duration', models.DurationField(blank=True, null=True)),
                ('bounce_rate', models.FloatField(default=0.0)),
                ('new_visitors', models.PositiveIntegerField(default=0)),
                ('returning_visitors', models.PositiveIntegerField(default=0)),
                ('direct_traffic', models.PositiveIntegerField(default=0)),
                ('google_traffic', models.PositiveIntegerField(default=0)),
                ('facebook_traffic', models.PositiveIntegerField(default=0)),
                ('whatsapp_traffic', models.PositiveIntegerField(default=0)),
                ('referral_traffic', models.PositiveIntegerField(default=0)),
                ('organic_traffic', models.PositiveIntegerField(default=0)),
                ('desktop_visitors', models.PositiveIntegerField(default=0)),
                ('mobile_visitors', models.PositiveIntegerField(default=0)),
                ('tablet_visitors', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Statistics',
                'verbose_name_plural': 'Daily Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('total_visits', models.PositiveIntegerField(default=1)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('total_time_spent', models.DurationField(default=datetime.timedelta(0))),
                ('is_bot', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-last_visit'],
            },
        ),
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('direct', 'Direct'), ('google', 'Google'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('bing', 'Bing'), ('yahoo', 'Yahoo'), ('referral', 'Referral'), ('email', 'Email'), ('social', 'Social Media'), ('organic', 'Organic Search'), ('paid', 'Paid Search'), ('unknown', 'Unknown')], max_length=20)),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=100, null=True)),
                ('medium', models.CharField(blank=True, max_length=50, null=True)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_sources', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-first_visit'],
            },
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('page_views_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=100, null=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('path', models.CharField(max_length=500)),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
                ('referrer', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('exit_page', models.BooleanField(default=False)),
                ('bounce', models.BooleanField(default=False)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('form_submit', 'Form Submit'), ('download', 'Download'), ('video_play', 'Video Play'), ('scroll', 'Scroll'), ('hover', 'Hover'), ('custom', 'Custom')], max_length=20)),
                ('event_name', models.CharField(max_length=100)),
                ('event_value', models.CharField(blank=True, max_length=200, null=True)),
                ('page_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.visitor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
