# Generated by Django 5.0.1 on 2025-10-05 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_specialization', models.CharField(max_length=100)),
                ('clinic_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('budget_range', models.CharField(blank=True, max_length=50)),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('results', models.TextField()),
                ('testimonial', models.TextField(blank=True)),
                ('featured_image', models.ImageField(upload_to='case_studies/')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='case_studies/before/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='case_studies/after/')),
                ('website_traffic_increase', models.CharField(blank=True, max_length=50)),
                ('patient_inquiries_increase', models.CharField(blank=True, max_length=50)),
                ('social_media_growth', models.CharField(blank=True, max_length=50)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('clinic_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('website_url', models.URLField()),
                ('website_type', models.CharField(max_length=50)),
                ('technologies_used', models.CharField(blank=True, max_length=200)),
                ('screenshot', models.ImageField(upload_to='doctor_websites/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='doctor_websites/logos/')),
                ('launch_date', models.DateField()),
                ('monthly_visitors', models.PositiveIntegerField(blank=True, null=True)),
                ('patient_inquiries', models.PositiveIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doctor Website',
                'verbose_name_plural': 'Doctor Websites',
                'ordering': ['order', '-launch_date'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='case_studies/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.casestudy')),
            ],
            options={
                'verbose_name': 'Case Study Image',
                'verbose_name_plural': 'Case Study Images',
                'ordering': ['order'],
            },
        ),
    ]
